config/routes.rb
Tryloop::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "static_pages/home"

  get "static_pages/help"

  get "users/new"

  root                to: 'static_pages#home'
  match '/help',      to: 'static_pages#help'
  match '/prepare',   to: 'static_pages#prepare'
  match '/explore',   to: 'static_pages#explore'
  match '/reflect',   to: 'static_pages#reflect'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new' 
  match '/signout',   to: 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://triptagg.herokuapp.com/">TripTagg</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("smallblacktriptagglogo.png", alt: "TripTagg"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home",    root_path %></li>
          <% if signed_in? %>
          <li class="<%= 'active' if current_page?(prepare_path) %>"><%= link_to "1. Prepare", prepare_path %></li>
          
          <li class="<%= 'active' if current_page?(explore_path) %>"><%= link_to "2. Explore", explore_path %></li>
          <li class="<%= 'active' if current_page?(reflect_path) %>"><%= link_to "3. Reflect", reflect_path %></li>
          <li class="<%= 'active' if current_page?(help_path) %>"><%= link_to "Help",    help_path %></li>
          
            <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Users", users_path %></li>
            
            <li id="fat-menu" class="dropdown <%= 'active' if 
                    current_page?(current_user) or
                    current_page?(edit_user_path(current_user)) %>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                
                <li class="divider"></li>
                
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html> 